### PR TITLE
updated with a nice texture of wiki block

### PR DESCRIPTION
**Pull request by tanmayameher**
Hi Kaeza, 

I updated the texture of wiki block and put the texture names in wikilib.lua file

Tested in single player mode working fine :+1: 
Hope you like it. :)

Thanks and regards,
TM

### CODE REVIEW

**Comment by sofar** [comment]
Well, if I'm honest I wouldn't use the letters `wiki` on the block.

Something that looks like a posterboard, perhaps. E.g. a texture like this maybe:

**Comment by kaeza** [comment]
I agree with sofar. The block definitely needs textures to distinguish it from the regular bookcase but these are not what I'm looking for.

The note board idea is nice.

**Comment by tanmayameher** [comment]
well that's good idea. But problem with posterboard is that when you get into the level of pixel; i don't think that will look like a poster board at all. It will probably look like some white dots at random on a brown surface. Therefore, i put a word (in this case "wiki") all around and a book look alike texture on top. These are only on half of it; the other half i left out. so, it looks like a bookshelf. But anyways, if you can make it look like a posterboard at pixel level; it will definitely look good. :+1: )

**Comment by sofar** [comment]
That was like, 3 minutes of work.

**Comment by tanmayameher** [comment]
well if that look good and like a poster board; then yes good work. good luck. have fun :)

**Pull request closed without merging**
